modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "nebular"
version = "${version}"
displayName = "Nebular"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "Nebular.png"

[[dependencies.nebular]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nebular]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.nebular]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="AFTER"
side="BOTH"

[[dependencies.nebular]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.1.1-beta.3,)"
ordering = "AFTER"
side = "BOTH"